---
- hosts: webservers
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
      become: yes
      tags: install
    - name: start nginx
      service:
          name: nginx
          state: started
      become: yes
      tags: install
    - name: copy the nginx config file and restart nginx
      copy:
        src: /var/lib/jenkins/ansible-nginx/files/static_site.cfg
        dest: /etc/nginx/sites-available/static_site.cfg
      become: yes
      tags: setup
    - name: create symlink
      file:
        src: /etc/nginx/sites-available/static_site.cfg
        dest: /etc/nginx/sites-enabled/default
        state: link
      become: yes
      tags: setup
    - name: copy the content of the web site
      copy:
        src: /var/lib/jenkins/ansible-nginx/files/static-site-src/
        dest: /home/foo/static-site
      tags: setup
    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: yes
      setup: tags
